### PR TITLE
Add lockfile cleanup to dbDisconnect

### PR DESCRIPTION
**Pull request by n8layman**

### CODE REVIEW

**Review by noamross — APPROVED** [review]

**Comment by n8layman** [comment]
I spoke with the DOLT team on discord and they suggested better ways to kill the process. They also said using the CLI while a server is running can do unexpected things which is why they implemented the lock file.

**Comment by n8layman** [comment]
> Is this for the case that you found the process but don't have the dolt database directory? `ps::ps_cwd()` returns the working directory of the process, which should be the same thing.

Yeah. I just changed it so dkill accepts the directory as an argument. ps::ps_cwd() seems better. I'll put it back and switch to that.

**Comment by n8layman** [comment]
I also tested that ps_cwd does return the appropriate directory. dkill should now clean up the lock file and the dtra-ml automation succeeded. I'll merge this in and close the issue.

**Comment by noamross** [comment]
Nice work!

**Pull request merged**
